description: >- 
  Welcome to my personal website, where I share my research publications, tutorials, and topics I am passionate about in robotics, control, and intelligent systems.
baseurl: "" 
url: "https://NiloufarAmiri.github.io"

github_username:  NiloufarAmiri

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - publications.md
  - awards.md